version: "3"
services:
  code:
    image: codercom/code-server
    restart: unless-stopped
    command: code-server
    env_file: .env
    ports:
      - "8443:8080"
    volumes:
      - /Users/sho/sho/Develop/Github:/home/coder/project
      - ./code-server:/home/coder/.local/share/code-server
      - ~/.gitconfig:/home/coder/.gitconfig:ro
      - ~/.ssh:/home/coder/.ssh:ro
